Initial release

diff --git a/copy-nvidia-libs b/copy-nvidia-libs
--- a/copy-nvidia-libs
+++ b/copy-nvidia-libs
@@ -30,34 +30,24 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ `dpkg -l | grep nvidia | grep nonglvnd` ]; then
-	libGL=
-	for dir in $LIB_DIRS; do
-	    _libGL="/usr/lib/$dir/libGL.so.1"
-	    if [ -f "$_libGL" ]; then
-		libGL="$_libGL"
-	    fi
-	done
+libGL=
+for dir in $LIB_DIRS; do
+    _libGL="/usr/lib/$dir/libGL.so.1"
+    if [ -f "$_libGL" ]; then
+	libGL="$_libGL"
+    fi
+done
 
-	if [ -z "$libGL" ]; then
-	    echo "error: could not find libGL.so.1" >&2
-	    exit 1
-	fi
-
-	# follow link to find out what is the real lib providing libGL.so.1
-	# then find the subdir containing the nvidia libs
-	rel_libGL_dir="$(dirname "$libGL")"
-	libGL_dir="$(dirname "$(readlink -f "$libGL")")"
-	nvidia_private="${libGL_dir#$rel_libGL_dir/}"
-else
-        # Find nvidia folder
-        libGLX_nvidia="/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0"
-        rel_libGLX_dir="$(dirname "$libGLX_nvidia")"
-        libGLX_dir="$(dirname "$(readlink -f "$libGLX_nvidia")")"
-        nvidia_private="${libGLX_dir#$rel_libGLX_dir/}"
-        libGL_dir=$libGLX_dir
+if [ -z "$libGL" ]; then
+    echo "error: could not find libGL.so.1" >&2
+    exit 1
 fi
 
+# follow link to find out what is the real lib providing libGL.so.1
+# then find the subdir containing the nvidia libs
+rel_libGL_dir="$(dirname "$libGL")"
+libGL_dir="$(dirname "$(readlink -f "$libGL")")"
+nvidia_private="${libGL_dir#$rel_libGL_dir/}"
 
 case $nvidia_private in
     nvidia/*)
@@ -84,7 +74,7 @@ case $pkgs_list in
 esac
 
 # Add needed packages containing lib outside nvidia folder
-pkgs_list="$(echo "$pkgs_list libnvidia-legacy-390xx-glcore:amd64 ")"
+pkgs_list="$(echo "$pkgs_list libnvidia-glcore:amd64 libnvidia-compiler:amd64 libnvidia-eglcore:amd64 libnvidia-fatbinaryloader:amd64 libglvnd0:amd64")"
 
 for pkg in $pkgs_list; do
     dpkg -L $pkg | while read file; do
@@ -121,44 +111,4 @@ for pkg in $pkgs_list; do
     done
     # This is always needed
     printf "mkdir -p '%s//usr/lib/nvidia/edc'\n" "$CHROOT_PATH"
-done | sort -u | sort -r
-
-# Packages linked to GLVND
-pkg_glvnd_list="$(echo "libgl1:i386 libgl1:amd64 libglx0:amd64 libglx0:i386 libglvnd0:i386 libglvnd0:amd64")"
-for pkg in $pkg_glvnd_list; do
-    dpkg -L $pkg | while read file; do
-	case $file in
-	    /usr/lib/*)
-		if ! [ -f "$file" ]; then
-		    continue
-		fi
-
-		dest="$file"
-
-		if $multiarch_dest; then
-		    # Transform it into a multi-arch path, if needed
-		    if echo "$dest" | grep -vqE '^/usr/lib/[a-z0-9_]+-[a-z0-9_]+-[a-z0-9_]+/'; then
-			dest="/usr/lib/x86_64-linux-gnu/${dest#/usr/lib/}"
-		    fi
-		else
-		    # Transform it into a mono-arch path, if needed
-		    if echo "$dest" | grep -qE '^/usr/lib/[a-z0-9_]+-[a-z0-9_]+-[a-z0-9_]+/'; then
-			dest="/usr/lib/${dest#/usr/lib/*-*-*/}"
-		    fi
-		fi
-
-		dest="$CHROOT_PATH/${dest}"
-		dest_dir="$(dirname "$dest")/nvidia/glvnd/"
-		dest="$dest_dir/$(basename $dest)"
-
-		printf "mkdir -p '%s'\n" "$dest_dir"
-		printf "copy_host_files '%s' '%s' '%s'\n" "$(basename "$file")" "$(dirname "$file")" "$(dirname "$dest")"
-	    ;;
-	    *)
-		: ignore
-	    ;;
-	esac
-    done
-    # This is always needed
-    printf "mkdir -p '%s//usr/lib/nvidia/glvnd'\n" "$CHROOT_PATH"
 done | sort -u | sort -r
diff --git a/script-scibian.d/99nvidia b/script-scibian.d/99nvidia
--- a/script-scibian.d/99nvidia
+++ b/script-scibian.d/99nvidia
@@ -65,77 +65,77 @@ if [ $STAGE = "setup-start" ] && [ "$(basename "$0")" = "99check" ]; then
 	    touch "$nvidia_flagd/update"
 	fi
 
-	APT_TOLERANCE=tolerant_apt
+	APT_TOLERANCE=intolerant_apt
+	if ! install_pkg glx-alternative-nvidia; then
+	    warn "failed to install glx-alternative-nvidia"
+	    APT_TOLERANCE=tolerant_apt
+	else
+	    APT_TOLERANCE=tolerant_apt
 
-	rm -rf "$CHROOT_PATH/usr/lib/nvidia/edc"
-	rm -rf "$CHROOT_PATH/usr/lib/x86_64-linux-gnu/nvidia/edc"
-	rm -rf "$CHROOT_PATH/usr/lib/i386-linux-gnu/nvidia/edc"
+	    rm -rf "$CHROOT_PATH/usr/lib/nvidia/edc"
+	    rm -rf "$CHROOT_PATH/usr/lib/x86_64-linux-gnu/nvidia/edc"
+	    rm -rf "$CHROOT_PATH/usr/lib/i386-linux-gnu/nvidia/edc"
 
-	cnl_options='--multiarch-target'
+	    cnl_options='--multiarch-target'
 
-	# Copy the libraries
-	if ! install_cmds="$(/usr/share/edc-base/copy-nvidia-libs $cnl_options)"; then
-	    fatal "failed to find the NVIDIA libraries to be copied"
-	fi
-
-	eval "$install_cmds"
-
-	# nvidia-alternatives handling
-	# paths relative to the EDC
-	edc_rel_alt_scriptd="/usr/share/edc-scibian"
-	edc_rel_alt_script="$edc_rel_alt_scriptd/nvidia-alternative"
-	# paths relative to our rootfs
-	edc_alt_scriptd="$CHROOT_PATH/$edc_rel_alt_scriptd"
-	edc_alt_script="$CHROOT_PATH/$edc_rel_alt_script"
-
-	# Remove the current alternatives
-	if [ -x "$edc_alt_script" ]; then
-	    chroot "$CHROOT_PATH" "$edc_rel_alt_script" remove
-	fi
-
-	found_candidate=false
-	info "looking for $edc_name $edc_version"
-	for candidate in $edc_name $edc_version; do
-	    alt_script="/usr/share/edc-scibian/config/nvidia/$candidate"
-
-	    if ! [ -f "$alt_script" ]; then
-		continue
+	    # Copy the libraries
+	    if ! install_cmds="$(/usr/share/edc-base/copy-nvidia-libs $cnl_options)"; then
+		fatal "failed to find the NVIDIA libraries to be copied"
 	    fi
 
-	    # cleanup the old libGL libs before setting up with update-alternative
-	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/lib/x86_64-linux-gnu/libGL.so*'
-	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/lib/i386-linux-gnu/libGL.so*'
-	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/lib/x86_64-linux-gnu/libGLdispatch.so*'
+	    eval "$install_cmds"
 
-	    mkdir -p "$edc_alt_scriptd"
-	    cp -a "$alt_script" "$edc_alt_script"
-	    chmod +x "$edc_alt_script"
-	    chroot "$CHROOT_PATH" "$edc_rel_alt_script"
-	    found_candidate=true
-	    break
-	done
+	    # nvidia-alternatives handling
+	    # paths relative to the EDC
+	    edc_rel_alt_scriptd="/usr/share/edc-scibian"
+	    edc_rel_alt_script="$edc_rel_alt_scriptd/nvidia-alternative"
+	    # paths relative to our rootfs
+	    edc_alt_scriptd="$CHROOT_PATH/$edc_rel_alt_scriptd"
+	    edc_alt_script="$CHROOT_PATH/$edc_rel_alt_script"
 
-	    # convert libGLdispatch.so.0 to link
-	    [ -f $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 ] && \
-		    [ -f $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0 ] && \
-		    ln -sf /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0 $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 && \
-		    ln -sf /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0 $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so
-	
-	# Make sure the triggers are executed:
-	chroot "$CHROOT_PATH" /bin/sh -c 'dpkg --triggers-only --pending'
+	    # Remove the current alternatives
+	    if [ -x "$edc_alt_script" ]; then
+		chroot "$CHROOT_PATH" "$edc_rel_alt_script" remove
+	    fi
 
-	# Useless actually ? 
-	# chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/local/lib/x86_64-linux-gnu/libnvidia-*.so*'
-	# chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/local/lib/i386-linux-gnu/libnvidia-*.so*'
+	    found_candidate=false
+	    info "looking for $edc_name $edc_version"
+	    for candidate in $edc_name $edc_version; do
+		alt_script="/usr/share/edc-scibian/config/nvidia/$candidate"
 
-	ln -sf /usr/lib/x86_64-linux-gnu/libGL.so.1 $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGL.so
+		if ! [ -f "$alt_script" ]; then
+		    continue
+		fi
 
-	chroot "$CHROOT_PATH" /sbin/ldconfig || :
+		mkdir -p "$edc_alt_scriptd"
+		cp -a "$alt_script" "$edc_alt_script"
+		chmod +x "$edc_alt_script"
+		chroot "$CHROOT_PATH" "$edc_rel_alt_script"
+		found_candidate=true
+		break
+	    done
 
-	if $found_candidate; then
-	    touch "$nvidia_flagd/$edc_name"
-	else
-	    fatal "could not find NVIDIA alternatives script"
+		# convert libGLdispatch.so.0 to link
+		[ -f $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 ] && \
+			[ -f $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0 ] && \
+			ln -sf /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0 $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 && \
+			ln -sf /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0 $CHROOT_PATH/usr/lib/x86_64-linux-gnu/libGLdispatch.so
+	    # Make sure the triggers are executed:
+	    chroot "$CHROOT_PATH" /bin/sh -c 'dpkg --triggers-only --pending'
+
+	    # cleanup the old libGL libs
+	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/local/lib/x86_64-linux-gnu/libGL.so*'
+	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/local/lib/x86_64-linux-gnu/libnvidia-*.so*'
+	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/local/lib/i386-linux-gnu/libGL.so*'
+	    chroot "$CHROOT_PATH" /bin/sh -c 'rm -f /usr/local/lib/i386-linux-gnu/libnvidia-*.so*'
+
+	    chroot "$CHROOT_PATH" /sbin/ldconfig || :
+
+	    if $found_candidate; then
+		touch "$nvidia_flagd/$edc_name"
+	    else
+		fatal "could not find NVIDIA alternatives script"
+	    fi
 	fi
     fi > "$nvidia_lock/nvidia.$edc_name"
     set +u
